name: C# CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v6
    - uses: microsoft/setup-msbuild@v2
    - name: Generate binaries
      run: |
        dotnet restore CFWSetuper.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU"
        MSBuild.exe CFWSetuper.csproj /p:Configuration=${{ matrix.configuration }}
    - name : Generate artifact
      if: matrix.configuration == 'Release'
      run: |
        bin\Release\net10.0\CFWSetuper.exe
    - uses: actions/upload-artifact@v6
      if: matrix.configuration == 'Release'
      with:
        name: CFW Switch
        path: CFW Switch
    - uses: actions/upload-artifact@v6
      if: matrix.configuration == 'Release'
      with:
        name: hekate bin
        path: hekate bin